version: '3'
services:
  ambweb:
    build: ./ambweb
    command: /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "${AMBWEB_PORT:-8000}:8000"
    depends_on:
      - ambweb_db
    volumes:
      - ./ambweb:/code

  amb_client:
    build: ./ambp3client
    command: python /code/amb_client.py -f /code/${AMB_LOCAL_CONF:-local_conf.yaml}
    depends_on:
      - karts_db
    volumes:
      - ./ambp3client:/code

  amb_laps:
    build: ./ambp3client
    command: python /code/amb_laps.py -f /code/${AMB_LOCAL_CONF:-local_conf.yaml}
    depends_on:
      - karts_db
    volumes:
      - ./ambp3client:/code

  ambweb_db:
    image: "mariadb:10.4"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
    - .env_db
    environment:
        MYSQL_ROOT_PASSWORD: '${AMBWEB_MYSQL_ROOT_PASSWORD:-test}'
        MYSQL_USER: '${AMBWEB_MYSQL_USER:-test_user}'
        MYSQL_PASSWORD: '${AMBWEB_MYSQL_PASSWORD:-test_password}'
        MYSQL_DATABASE: '${AMBWEB_MYSQL_DATABASE:-test_database}'
    volumes:
      - ./mysql-datadir/ambweb:/var/lib/mysql
    ports:
      - "${AMBWEB_MYSQL_PORT:-3306}:3306"

  karts_db:
    image: "mariadb:10.4"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
    - .env_db
    environment:
        MYSQL_ROOT_PASSWORD: '${KARTS_MYSQL_ROOT_PASSWORD:-test}'
        MYSQL_USER: '${KARTS_MYSQL_USER:-test_user}'
        MYSQL_PASSWORD: '${KARTS_MYSQL_PASSWORD:-test_password}'
        MYSQL_DATABASE: '${KARTS_MYSQL_DATABASE:-test_database}'
    volumes:
      - ./mysql-datadir/karts:/var/lib/mysql
      - ./mysql-config/karts:/etc/mysql/conf.d
    ports:
      - "${KARTS_MYSQL_PORT:-3307}:3307"

  amb_test_server:
    build: ./ambp3client
    command: python /code/test_server/test_server.py ${AMB_TEST_SERVER_FILE:-/code/test_server/out.log} -l ${AMB_TEST_SERVER:-0.0.0.0} -p ${AMB_TEST_SERVER_PORT:-12001}
    depends_on:
    - karts_db
    volumes:
      - ./ambp3client:/code
