version: '3'
services:
  ambweb:
    build: ./ambweb
    command: /code/manage.py runserver 0.0.0.0:8000  
    environment:
    - PYTHONUNBUFFERED=TRUE
    ports:
    - "${AMBWEB_LISTEN_IP:-127.0.0.1}:${AMBWEB_PORT:-8000}:8000"
    depends_on:
    - ambweb_db
    volumes:
    - ./ambweb:/code:Z
    - ./AMBWEB_LOG:/var/log/AMB/

  amb_client:
    build: ./ambp3client 
    command: python /code/amb_client.py -f /code/${AMB_LOCAL_CONF:-local_conf.yaml} 
    depends_on:
    - karts_db
    volumes:
    - ./ambp3client:/code:Z
    - ./AMB_CLIENT_LOGS:/tmp


  amb_laps:
    build: ./ambp3client 
    command: python /code/amb_laps.py -f /code/${AMB_LOCAL_CONF:-local_conf.yaml}
    depends_on:
    - karts_db
    volumes:
    - ./ambp3client:/code:Z
    - ./AMB_LAPS_LOGS:/tmp

  ambweb_db:
    image: "mariadb:10.4"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
    - .env_ambweb_db
    volumes:
    - ./mysql-datadir/ambweb:/var/lib/mysql
    ports:
    - "${AMBWEB_DB_LISTEN_IP:-127.0.0.1}:${AMBWEB_MYSQL_PORT:-3306}:3306"

  karts_db:
    image: "mariadb:10.4"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
    - .env_karts_db
    volumes:
    - ./mysql-datadir/karts:/var/lib/mysql
    - ./mysql-config/karts:/etc/mysql/conf.d
    ports:
    - "${KARTS_DB_LISTEN_IP:-127.0.0.1}:${KARTS_MYSQL_PORT:-3307}:3307"

#  amb_test_server:
#    build: ./ambp3client
#    command: python /code/test_server/test_server.py ${AMB_TEST_SERVER_FILE:-/tmp/amb_test_data} -l ${AMB_TEST_SERVER:-0.0.0.0} -p ${AMB_TEST_SERVER_PORT:-12001}
#    depends_on:
#    - karts_db
#    volumes:
#    - ./ambp3client:/code:z
#    - ./AMB_TEST_SERVER:/tmp
#    ports:
#    - "${AMB_TEST_SERVER_PORT:-12001}:${AMB_TEST_SERVER_PORT:-12001}"


